language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.9-xenial -y
  - sudo apt-get update -qq

install:
  - # Qt 5.12 has OpenSSL support while Qt 5.15 does not in this packages
  - sudo apt-get -y install build-essential libgl1-mesa-dev xvfb qt512base
  - sudo apt-get -y install libboost-system-dev libboost-python-dev libboost-chrono-dev libboost-random-dev libssl-dev
  - source /opt/qt*/bin/qt*-env.sh

script:
  - wget -q "https://github.com/arvidn/libtorrent/releases/download/libtorrent-1.2.8/libtorrent-rasterbar-1.2.8.tar.gz"
  - tar -xvf libtorrent-rasterbar-1.2.8.tar.gz
  - cd libtorrent-rasterbar-1.2.8
  - mkdir build
  - cd build
  - cmake ..
  - make -j$(nproc)
  - sudo make install -j$(nproc)
  - cd ..
  - cd ..
  - sudo ln -s /usr/local/lib/libtorrent-rasterbar.so.1.2.8 /usr/lib/libtorrent-rasterbar.so.10
  - mkdir build-qmake ; cd build-qmake # Check if it builds as a library using qmake.
  - qmake ..
  - make -j$(nproc)
  - make clean
  - qmake "CONFIG+=LOGGING_DISABLED" ..
  - make -j$(nproc) # test if build succeeds without log support
  - make clean
  - qmake "CONFIG+=NO_GUI" ..
  - make -j$(nproc) # test if build succeeds without gui support
  - make clean
  - qmake "CONFIG+=LOGGING_DISABLED" "CONFIG+=NO_GUI" ..
  - make -j$(nproc) # test if build succeeds without gui and log support
  - qmake "CONFIG+=DECENTRALIZED_UPDATE_ENABLED" ..  
  - make -j$(nproc) # test if build succeeds with libtorrent in qmake build config
  - cd ..
  - mkdir build-cmake ; cd build-cmake # Check if it builds as a library using cmake.
  - cmake ..
  - make -j$(nproc)
  - cd ..
  - rm -rf build-cmake
  - mkdir build-cmake ; cd build-cmake
  - cmake -DLOGGING_DISABLED=ON ..
  - make -j$(nproc)
  - cd ..
  - rm -rf build-cmake
  - mkdir build-cmake ; cd build-cmake
  - cmake -DNO_GUI=ON ..
  - make -j$(nproc)
  - cd ..
  - rm -rf build-cmake
  - mkdir build-cmake ; cd build-cmake
  - cmake -DLOGGING_DISABLED=ON -DNO_GUI=ON ..
  - make -j$(nproc)
  - cd ..
  - rm -rf build-cmake
  - mkdir build ; cd build
  - cmake -DDECENTRALIZED_UPDATE_ENABLED=ON ..
  - make -j$(nproc)
  - sudo make install 
  - cd ..
  - rm -rf build
  - cd tests
  - cmake -DDECENTRALIZED_UPDATE_ENABLED=ON .
  - make -j$(nproc)
  - Xvfb :100 -ac &
  - export DISPLAY=:100.0
  - ./tests
  - cd ..
  - mkdir build
  - cd build
  - cmake -DBUILD_AS_PLUGIN=ON ..
  - make -j$(nproc)

after_success:
  - wget "https://github.com/probonopd/uploadtool/raw/master/upload.sh"
  - bash upload.sh libQAppImageUpdate.so

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
